#!/bin/bash
echo "🔍 Competitor Keyword Analysis (SEMrush free trial or manual research)"
echo "Suggested tools:"
echo "  - Google Keyword Planner"
echo "  - SEMrush (free tier)"
echo "  - Ahrefs Webmaster Tools (free)"
echo ""
echo "Top competitors to analyse:"
echo "  1. WebFX India"
echo "  2. Techmagnate"
echo "  3. PageTraffic"
echo "  4. ThatWare"
echo "  5. SEOTonic"
echo ""
echo "Use this command to extract keywords from their meta tags:"
echo "  curl -s https://competitor.com | grep -oP '(?<=<meta name=\"keywords\" content=\")[^\"]+'"
